main.plugins.home_base.enabled = true
main.plugins.home_base.minimum_signal_strength = -75
main.plugins.home_base.password= 'REDACTED_SEE_UPSTREAM_HAD_REAL_VALUE'
main.plugins.home_base.ssid = 'B33zh1v3!'
